version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: demo_postgres
    restart: always
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
