spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/demo_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
  sql:
    init:
      mode: always   # always / embedded / never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
